/**
 * Bakes the Daily Roll: for each day, searches far more attempts than the
 * game could on the spot for floors that meet the bar, and records which
 * attempt built each floor in src/meta/daily-picks.ts. The game then
 * rebuilds just that attempt.
 *
 *   npx tsx tools/daily-bake.ts <days> [parts]   (default 400 days, 4 parts in parallel)
 *   npx tsx tools/daily-bake.ts --part <i> <parts> <days> <out.json>   (one part; used internally)
 */
import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { defaultRules } from '../src/content/register';
import { generateLevel } from '../src/gen/generate';
import { DAILY_FLOORS, DAILY_THEMES_FROM, addDays, dailyFloorParams } from '../src/meta/daily';

const ATTEMPTS = 1500;
type Row = { day: number; picks: number[]; missed: number[] };

function bakePart(part: number, parts: number, days: number, out: string): void {
  const rules = defaultRules();
  const rows: Row[] = [];
  for (let day = part; day < days; day += parts) {
    const date = addDays(DAILY_THEMES_FROM, day);
    const row: Row = { day, picks: [], missed: [] };
    for (let floor = 1; floor <= DAILY_FLOORS; floor++) {
      const { pick: _pick, maxAttempts: _max, ...p } = dailyFloorParams(date, floor);
      const g = generateLevel(rules, { ...p, maxAttempts: ATTEMPTS });
      row.picks.push(g.pick ?? 0);
      if (!g.inBand) row.missed.push(floor);
    }
    rows.push(row);
    writeFileSync(out, JSON.stringify(rows));
    console.log(
      `${date} ${row.picks.join(' ')}${row.missed.length ? ` missed ${row.missed}` : ''}`,
    );
  }
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args[0] === '--part') {
    bakePart(Number(args[1]), Number(args[2]), Number(args[3]), args[4]!);
    return;
  }
  const days = Number(args[0] ?? 400);
  const parts = Number(args[1] ?? 4);
  const files = Array.from({ length: parts }, (_, i) => join(tmpdir(), `daily-bake-${i}.json`));
  await Promise.all(
    files.map(
      (out, i) =>
        new Promise<void>((done, fail) => {
          const child = spawn(
            process.execPath,
            [
              '--import',
              'tsx',
              process.argv[1]!,
              '--part',
              String(i),
              String(parts),
              String(days),
              out,
            ],
            { stdio: 'inherit' },
          );
          child.on('exit', (code) => (code === 0 ? done() : fail(new Error(`part ${i}: ${code}`))));
        }),
    ),
  );
  const rows = files
    .flatMap((f) => JSON.parse(readFileSync(f, 'utf8')) as Row[])
    .sort((a, b) => a.day - b.day);
  const missed = rows.filter((r) => r.missed.length);
  const table = rows.map((r) => r.picks.map((n) => n.toString(36)).join('.')).join(',');
  writeFileSync(
    'src/meta/daily-picks.ts',
    `/**
 * Generated by tools/daily-bake.ts: for each day from DAILY_PICKS_FROM, the
 * attempt that builds each of its three floors (base 36, floors split by
 * '.', days by ','). Don't edit by hand.
 */
export const DAILY_PICKS_FROM = '${DAILY_THEMES_FROM}';
export const DAILY_PICKS =
  '${table}';
`,
  );
  console.log(`${rows.length} days baked; ${missed.length} with a floor below the bar.`);
}

void main();
